
name: Generate Snake Game

on:
  schedule: # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    name: Generate Snake Game SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Amansingh675  # <-- replace with your GitHub username
          outputs: dist/snake.svg

      - name: Push Generated Snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
